# Generated by Django 4.0.2 on 2022-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags_recipe',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Tag'),
        ),
    ]
