# Generated by Django 4.0.2 on 2022-04-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.tag'),
        ),
    ]
