# Generated by Django 4.0.2 on 2022-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_teste_remove_recipe_tags_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags_recipe',
            new_name='tag',
        ),
    ]
