# Generated by Django 4.0.2 on 2022-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_tags_recipe_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Tag'),
        ),
    ]
