# Generated by Django 4.0.2 on 2022-04-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
