# Generated by Django 3.2 on 2022-04-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
